#!/bin/bash
set -e

../verify-docker-versions

export INTEGRATION_VERSION=$(git describe --tags --abbrev=0)
export MENDER_ARTIFACT_VERSION=$(../extra/release_tool.py -g mender-artifact)
export MENDER_VERSION=$(../extra/release_tool.py -g mender)
export MENDER_DEB_PACKAGE_VERSION=$MENDER_VERSION

exec docker-compose \
     -p menderproduction \
     -f ../docker-compose.yml \
     -f ../docker-compose.storage.minio.yml \
     -f ./prod.yml \
     "$@"
