#!/bin/bash -e

SELFDIR=$(dirname "$(readlink -f "$0")")
SCRIPT=${SCRIPT:=./run}

SERVICES="\
  mender-inventory \
  mender-useradm \
  mender-device-auth \
  mender-device-adm \
  mender-deployments \
"

DB_SERVICES="\
  mender-mongo-useradm \
  mender-mongo-inventory \
  mender-mongo-device-adm \
  mender-mongo-device-auth \
  mender-mongo-deployments \
"

# stop service that are using DBs
# shellcheck disable=SC2086
${SCRIPT} stop ${SERVICES}

# start mongodb container
# shellcheck disable=SC2016
DUMP_PATH=$PWD ${SCRIPT} up -d mender-mongo

# wait for mongodb
sleep 10

# shellcheck disable=SC2016
DUMP_PATH=$PWD ${SCRIPT} -f ${SELFDIR}/migration-helper.yml run \
         --rm \
         -e DB_SERVICES="${DB_SERVICES}" \
         mongo-helper \
         sh -c 'for s in ${DB_SERVICES}; do mongorestore -h mender-mongo --drop "/srv/db-dump/$s"; done'
