version: '2.3'
services:

    #
    # mongo migration helper service
    #
    mongo-helper:
        image: mongo:5.0
        networks:
            - mender
        volumes:
          - ${DUMP_PATH}:/srv
