version: '2.1'
services:

    #
    # mongo migration helper service
    #
    mongo-helper:
        image: mongo:3.6
        networks:
            - mender
        volumes:
          - ${DUMP_PATH}:/srv
