
include:
  - component: gitlab.com/Northern.tech/Mender/mendertesting/commit-lint@master
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-license.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-python3-format.yml'

variables:
  LICENSE_HEADERS_IGNORE_FILES_REGEXP: '\./extra/gitdm.*'
