
include:
  - component: gitlab.com/Northern.tech/Mender/mendertesting/commit-lint@master
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-license.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-python3-format.yml'

variables:
  LICENSE_HEADERS_IGNORE_FILES_REGEXP: '\./extra/gitdm.*'
# Smoke test to verify requirements.txt are sane
test:integration-tests:requirements:
  stage: test
  rules:
    - changes:
      - tests/requirements-system/apk-requirements.txt
      - tests/requirements-python/python-requirements.txt
  # Use same image as in mender-qa
  image: docker:24.0.7-dind-alpine3.18
  script:
    # Get and install the integration test requirements
    - apk add $(cat tests/requirements-system/apk-requirements.txt)
    - pip install -r tests/requirements-python/python-requirements.txt
