#!/bin/bash


CLIENT="-f docker-compose.client.yml"
if [ -n "${NO_CLIENT}" ]; then
    unset CLIENT
    echo "-- disabling client containers"
fi

exec docker-compose \
     -f docker-compose.yml \
     -f docker-compose.storage.minio.yml \
     -f docker-compose.demo.yml \
     $CLIENT \
     "$@"
