services:
  #
  # monitor-client
  #
  mender-client:
    image: ${MENDER_CLIENT_ENTERPRISE_REGISTRY}/${MENDER_CLIENT_REPOSITORY}/${MENDER_MONITOR_QEMU_COMMERCIAL_IMAGE}:${MENDER_MONITOR_QEMU_COMMERCIAL_TAG}
    networks:
      - mender
    stdin_open: true
    tty: true
    privileged: true
    environment:
      - SERVER_URL=$SERVER_URL
      - TENANT_TOKEN=$TENANT_TOKEN
    blkio_config:
      weight: 100
    healthcheck:
      test: ["CMD-SHELL", "(exec 3<>/dev/tcp/127.0.0.1/22 && : <&3) 2>/dev/null"]
      interval: 5s
      timeout: 3s
      retries: 40
      start_period: 30s
networks:
  mender: {}
