services:

    #
    # mender-client
    #
    mender-client:
        networks:
            - default
        environment:
            - SERVER_URL=https://docker.mender.io
            - TENANT_TOKEN=$TENANT_TOKEN
