services:
  #
  # mender-client
  #
  mender-client:
    image: ${MENDER_CLIENT_REGISTRY}/${MENDER_CLIENT_REPOSITORY}/${MENDER_CLIENT_QEMU_EXTENDED_IMAGE}:${MENDER_CLIENT_QEMU_EXTENDED_TAG}
    networks:
      - mender
    stdin_open: true
    tty: true
    privileged: true
    environment:
      SERVER_URL:
      TENANT_TOKEN:
      QEMU_MEMORY: 512M
    blkio_config:
      weight: 100
    healthcheck:
      test: ["CMD-SHELL", "(exec 3<>/dev/tcp/127.0.0.1/22 && : <&3) 2>/dev/null"]
      interval: 5s
      timeout: 3s
      retries: 40
      start_period: 30s

networks:
  mender: {}
