services:
  #
  # mender-client
  #
  mender-client:
    image: ${MENDER_CLIENT_ENTERPRISE_REGISTRY}/${MENDER_CLIENT_REPOSITORY}/${MENDER_QEMU_ROFS_COMMERCIAL_IMAGE}:${MENDER_QEMU_ROFS_COMMERCIAL_TAG}
    networks:
      - default
    stdin_open: true
    tty: true
    privileged: true
    environment:
      SERVER_URL: "https://docker.mender.io"
      TENANT_TOKEN:
      QEMU_MEMORY: 512M

networks:
  default: {}
