#!/bin/sh

set -e

if [ $# -ne 2 ]; then
    echo "usage: gen-client-cert [tenant-name] [suffix]"
    exit 1
fi

CA_CERT="tls-poc-generated/$1.ca.crt"
CA_KEY="tls-poc-generated/$1.ca.key"

OUT_CLIENT_KEY="tls-poc-generated/$1.client.$2.key"
OUT_CLIENT_CSR="tls-poc-generated/$1.client.$2.csr"
OUT_CLIENT_CERT="tls-poc-generated/$1.client.$2.crt"

openssl genrsa -out $OUT_CLIENT_KEY 2048
openssl req -new -key $OUT_CLIENT_KEY -out $OUT_CLIENT_CSR

#pretend the serial number is unique
openssl x509 -req -days 365 -sha256 -in $OUT_CLIENT_CSR -CA $CA_CERT -CAkey $CA_KEY  -set_serial 1234 -out $OUT_CLIENT_CERT
