# This file lists software components that are part of a Mender release
# which are published with the global Mender product version. The versions here
# therefore point to the internal Git tags/branches. We keep this information as a
# docker-compose YAML file for parsing purposes.
services:

    #
    # backend open source services
    #
    mender-iot-manager:
        image: mendersoftware/iot-manager:1.3.0

    mender-deployments:
        image: mendersoftware/deployments:4.6.1

    mender-gui:
        image: mendersoftware/gui:3.7.2

    mender-device-auth:
        image: mendersoftware/deviceauth:3.6.0

    mender-inventory:
        image: mendersoftware/inventory:4.4.1

    mender-useradm:
        image: mendersoftware/useradm:1.22.2

    mender-deviceconnect:
        image: mendersoftware/deviceconnect:1.5.0

    mender-deviceconfig:
        image: mendersoftware/deviceconfig:1.4.0

    mender-reporting:
        image: mendersoftware/reporting:master

    mender-workflows-server:
        image: mendersoftware/workflows:2.6.1

    mender-workflows-worker:
        image: mendersoftware/workflows-worker:master

    mender-create-artifact-worker:
        image: mendersoftware/create-artifact-worker:1.4.0

    #
    # client repositories - container and image names are placeholders
    #
    mender:
        image: mendersoftware/mender:4.0.3

    mender-connect:
        image: mendersoftware/mender-connect:2.2.1

    mender-setup:
        image: mendersoftware/mender-setup:1.0.0

    mender-snapshot:
        image: mendersoftware/mender-snapshot:1.0.0

    mender-configure-module:
        image: mendersoftware/mender-configure-module:1.1.2

    monitor-client:
        image: mendersoftware/monitor-client:1.3.0

    mender-gateway:
        image: mendersoftware/mender-gateway:1.2.0

    mender-ci-workflows:
        image: mendersoftware/mender-ci-workflows:master
