# This file lists software components that are part of a Mender release
# which are published with the global Mender product version. The versions here
# therefore point to the internal Git tags/branches. We keep this information as a
# docker-compose YAML file for parsing purposes.
services:

    #
    # backend open source services
    #
    mender-iot-manager:
        image: mendersoftware/iot-manager:staging

    #mender-deployments:
        #image: mendersoftware/deployments:master

    mender-gui:
        image: mendersoftware/gui:staging

    # mender-device-auth:
    #     image: mendersoftware/deviceauth:master

    #mender-inventory:
        #image: mendersoftware/inventory:master

    #mender-useradm:
        #image: mendersoftware/useradm:master

    mender-deviceconnect:
        image: mendersoftware/deviceconnect:staging

    mender-deviceconfig:
        image: mendersoftware/deviceconfig:staging

    mender-reporting:
        image: mendersoftware/reporting:staging

    #mender-workflows-server:
        #image: mendersoftware/workflows:master

    #mender-workflows-worker:
        #image: mendersoftware/workflows-worker:master

    mender-create-artifact-worker:
        image: mendersoftware/create-artifact-worker:staging

    #
    # client repositories - container and image names are placeholders
    #
    mender:
        image: mendersoftware/mender:3.5.1

    mender-connect:
        image: mendersoftware/mender-connect:2.1.1

    mender-setup:
        image: mendersoftware/mender-setup:master

    mender-snapshot:
        image: mendersoftware/mender-snapshot:master

    mender-configure-module:
        image: mendersoftware/mender-configure-module:1.1.1

    monitor-client:
        image: mendersoftware/monitor-client:1.3.0

    mender-gateway:
        image: mendersoftware/mender-gateway:1.1.0

    mender-ci-workflows:
        image: mendersoftware/mender-ci-workflows:master
