# This file lists software components, and their versions, that are part of a
# Mender release, but which don't have Docker containers, and hence are not
# tracked there. It is written in the format of docker-compose purely for
# convenience; our tools will understand either one. So just ignore the
# 'services' tag.
services:
    mender-artifact:
        image: mendersoftware/mender-artifact:3.8.x

    mender-cli:
        image: mendersoftware/mender-cli:1.8.x

    mender-binary-delta:
        image: mendersoftware/mender-binary-delta:1.3.x

    mender-convert:
        image: mendersoftware/mender-convert:3.0.x

    meta-mender:
        image: mendersoftware/meta-mender:dunfell
