# This file lists software components, and their versions, that are part of a
# Mender release, but which don't have Docker containers, and hence are not
# tracked there. It is written in the format of docker-compose purely for
# convenience; our tools will understand either one. So just ignore the
# 'services' tag.
services:
    mender-artifact:
        image: mendersoftware/mender-artifact:3.6.1

    mender-cli:
        image: mendersoftware/mender-cli:1.7.0

    mender-connect:
        image: mendersoftware/mender-connect:1.2.0
