#!/bin/bash
# Removes any state from server to start clean.
# Mostly for demo purposes, be careful in production!

./verify-docker-versions

if [ $? -ne 0 ]; then
  exit 1
fi

sudo docker-compose ps | grep -q Up

if [ $? -eq 0 ]; then
  echo "Please stop the server before resetting."
  exit 1
fi

sudo ./demo rm -v
