#!/bin/bash
# wraps 'docker-compose up', first setting the
# env vars important for dev environments on OSX
# using docker-machine, assuming just one vm is started through it
set -e -o pipefail

./verify-docker-versions

# host entries we need to add
REQHOSTS="s3.docker.mender.io docker.mender.io"

DOCKER_HOST_IP="127.0.0.1"

log() {
    echo "--" "$*"
}

addhost() {
    local ip=$1
    local h=$2
    local tmpfile=$3
    echo "$ip $h # added by mender integration" >> "$tmpfile"
}

setuphosts() {
    if hash docker-machine 2>/dev/null; then
        # override default
        DOCKER_MACHINE_IP=$(docker-machine ip 2>/dev/null || true)
        if [ -n "$DOCKER_MACHINE_IP" ]; then DOCKER_HOST_IP=$DOCKER_MACHINE_IP; fi
    fi

    REQUIRED_HOSTFILE_IP=${DOCKER_HOST_IP:-"127.0.0.1"}

    tmpfile=$(mktemp /tmp/mender.XXXXX)
    # add hosts as needed
    for h in $REQHOSTS; do
        if ! grep "\s$h" /etc/hosts >/dev/null 2>&1 ; then
            addhost "$REQUIRED_HOSTFILE_IP" "$h" "$tmpfile"
        fi
    done

    if [ -s "$tmpfile" ] ; then
       log "adding the following entries to /etc/hosts:"
       sudo tee -a /etc/hosts < "$tmpfile"
    fi
    rm -f "$tmpfile"
}

rundocker() {
    # sudo -E ./demo scale mender-client=3  # NB! Typically run this just once, will add 3 clients each time
    sudo -E ./demo up
}

showhelp() {
    echo "usage: $(basename "$0") [-n] [-h]"
    echo "   -n   do not run docker-compose"
    echo "   -h   show help"
}

case "$1" in
    -h|--help)
        showhelp
        exit 0
        ;;
    -n)
        nodocker=y
        ;;
    *)
        ;;
esac

setuphosts
if [ "$nodocker" != "y" ]; then
    rundocker
fi
