#!/bin/sh
# wraps 'docker-compose up', first setting the
# env vars important for dev environments on OSX
# using docker-machine, assuming just one vm is started through it
set -u

hash docker-machine 2>/dev/null

if [ $? -eq 0 ]; then
    export DOCKER_HOST_IP=$(docker-machine ip)
else
    echo "docker-machine not found, DOCKER_HOST_IP not exported"
fi

REQUIRED_HOSTFILE_IP=${DOCKER_HOST_IP:-"127.0.0.1"}

if [ $(grep -c "${REQUIRED_HOSTFILE_IP}"'\s*'mender-artifact-storage.localhost /etc/hosts) -eq 0 ]; then
    # delete all lines referencing mender-artifact-storage.localhost

    echo "Since docker-compose is running inside a private network, and the fakeS3 server needs to be accessed, we need to modify /etc/hosts as a workaround"
    echo "Please enter your super user password below, when prompted."

    # OSX workaround
    TMP_DIR=$(mktemp -d "/tmp/mender.XXXXX")
    touch "$TMP_DIR"/tmp
    TMP_FILE=$TMP_DIR/tmp

    sudo awk '!/mender-artifact-storage.localhost/' /etc/hosts > "$TMP_FILE" && cat "$TMP_FILE" | sudo tee /etc/hosts >/dev/null


    echo "required mender-artifact-storage.localhost mapping not found in localhost, setting.."
    echo "${REQUIRED_HOSTFILE_IP} mender-artifact-storage.localhost"| sudo tee -a /etc/hosts >/dev/null

fi

sudo -E docker-compose up
