#!/bin/sh
# wraps 'docker-compose up', first setting the
# env vars important for dev environments on OSX

# using docker-machine, assuming just one vm is started through it
export DOCKER_HOST_IP=$(docker-machine ip)

sudo -E docker-compose up
