#!/bin/bash
# Updates to latest upstream docker compose and images.
# Mostly for demo purposes, be careful in production!

sudo docker-compose ps | grep -q Up

if [ $? -eq 0 ]; then
  echo "Please stop the server before updating."
  exit 1
fi

git pull
sudo docker-compose pull
