version: '2'
services:
    mender-conductor-ui:
        image: mendersoftware/conductor-ui:1.8.1
        environment:
            - WF_SERVER=http://mender-conductor:8080/api/
        depends_on:
            - mender-conductor
        networks:
            - mender
        ports:
            - "5000:5000"
