services:
  mender-client-3-6:
    # Testing image based on mender-3.6.3 with enlarged partitions
    image: mendersoftware/mender-client-qemu:mender-3.6.3-large-rootfs
    networks:
       - mender
    stdin_open: true
    tty: true
    privileged: true
    environment:
      - TENANT_TOKEN=$TENANT_TOKEN
