services:
  mender-client-3-0:
    image: mendersoftware/mender-client-qemu:3.0
    networks:
       - mender
    stdin_open: true
    tty: true
    privileged: true
    environment:
      - TENANT_TOKEN=$TENANT_TOKEN
    volumes:
      # NOTE: These volume mounts are only necessary for <= 3.0
      # Provision demo certificate
      - ./cert/cert.crt:/mnt/config/server.crt
      # Add updated setup that puts the new demo certificate in the global ca trust store
      - ./extra/integration-testing/setup-mender-configuration.py:/setup-mender-configuration.py

