services:
  mender-client-3-4:
    image: mendersoftware/mender-client-qemu:mender-3.4
    networks:
       - mender
    stdin_open: true
    tty: true
    privileged: true
    environment:
      - TENANT_TOKEN=$TENANT_TOKEN

