services:
  mender-client-3-7:
    image: mendersoftware/mender-client-qemu:mender-3.7
    networks:
       - mender
    stdin_open: true
    tty: true
    privileged: true
    environment:
      - TENANT_TOKEN=$TENANT_TOKEN
