version: '2.3'
services:
  mender-client-3-6:
    image: mendersoftware/mender-client-qemu:mender-3.6
    networks:
       - mender
    stdin_open: true
    tty: true
    privileged: true
    environment:
      - TENANT_TOKEN=$TENANT_TOKEN
