services:
  mender-client-3-6:
    image: lluiscampos/mender-client-qemu:mender-3.6-lluis-big
    networks:
       - mender
    stdin_open: true
    tty: true
    privileged: true
    environment:
      - TENANT_TOKEN=$TENANT_TOKEN
