version: '2'
services:

    #
    # mender-client
    #
    mender-client:
        networks:
            - mender
        volumes:
            - ./extra/signed-artifact-client-testing/config/artifact-verify-key.pem:/mnt/config/artifact-verify-key.pem:ro
