# Dynamic traefik configuration
http:
  #
  # Routers
  #
  routers:
    #
    # tenantadm
    #
    tenantadm:
      entrypoints: https
      middlewares: #{{- block "circuit-breaker" . -}}{{- if not (env "TESTING") }}
        - circuit-breaker #{{- end}}{{end}}
        - userauth
        - sec-headers
        - compression
      rule: "PathPrefix(`/api/management/{version:v[0-9]+}/tenantadm`)"
      service: tenantadm
      tls: true

    tenantadmSignup:
      entrypoints: https
      middlewares: #{{- template "circuit-breaker"}}
        - sec-headers
        - compression
      rule: >-
        Method(`OPTIONS`,`POST`) && Path(`/api/management/{version:v[0-9]+}/tenantadm/tenants`) ||
        Method(`OPTIONS`,`POST`) && Path(`/api/management/{version:v[0-9]+}/tenantadm/tenants/trial`)
      service: tenantadm
      tls: true

    #
    # auditlogs
    #
    auditlogs:
      entrypoints: https
      middlewares: #{{- template "circuit-breaker"}}
        - userauth
        - sec-headers
        - compression
        - json-error-responder1
        - json-error-responder4
      rule: "PathPrefix(`/api/management/{version:v[0-9]+}/auditlogs`)"
      service: auditlogs
      tls: true

    #
    # devicemonitor
    #
    devicemonitor:
      entrypoints: https
      middlewares: #{{- template "circuit-breaker"}}
        - devauth
        - sec-headers
        - compression
        - json-error-responder1
        - json-error-responder2
        - json-error-responder3
        - json-error-responder4
      rule: "PathPrefix(`/api/devices/{version:v[0-9]+}/devicemonitor`)"
      service: devicemonitor
      tls: true

    devicemonitorMgmt:
      entrypoints: https
      middlewares: #{{- template "circuit-breaker"}}
        - userauth
        - sec-headers
        - compression
        - json-error-responder1
        - json-error-responder2
        - json-error-responder3
        - json-error-responder4
      rule: "PathPrefix(`/api/management/{version:v[0-9]+}/devicemonitor`)"
      service: devicemonitor
      tls: true

  #
  # Services
  #
  services:
    tenantadm:
      loadBalancer:
        servers:
          - url: "http://mender-tenantadm:8080"

    auditlogs:
      loadBalancer:
        servers:
          - url: "http://mender-auditlogs:8080"

    deviceconnect:
      loadBalancer:
        servers:
          - url: "http://mender-deviceconnect:8080"

    deviceconfig:
      loadBalancer:
        servers:
          - url: "http://mender-deviceconfig:8080"

    devicemonitor:
      loadBalancer:
        servers:
          - url: "http://mender-devicemonitor:8080"
