FROM cypress/included:3.4.1
WORKDIR /e2e
RUN mkdir -p downloaded-tools && \
  curl -SL --fail "https://mender.s3-accelerate.amazonaws.com/temp_master/core-image-full-cmdline-qemux86-64.ext4" \
  -o core-image-full-cmdline-qemux86-64.ext4 && \
  curl -SL --fail "https://dgsbl4vditpls.cloudfront.net/mender-demo-artifact.mender" \
  -o mender-demo-artifact.mender && \
  curl -SL --fail "https://d1b0l86ne08fsf.cloudfront.net/mender-artifact/master/mender-artifact" \
  -o /usr/bin/mender-artifact && \
  chmod +x /usr/bin/mender-artifact
COPY package-lock.json package.json ./
ENV CI=1
RUN npm ci
COPY cypress.json cypress ./
RUN npx cypress verify
CMD npm run test