FROM cypress/included:3.4.0
RUN mkdir -p downloaded-tools && \
  curl -SL --fail "https://mender.s3-accelerate.amazonaws.com/temp_master/core-image-full-cmdline-qemux86-64.ext4" \
  -o core-image-full-cmdline-qemux86-64.ext4 && \
  curl -SL --fail "https://d1b0l86ne08fsf.cloudfront.net/mender-artifact/master/mender-artifact" \
  -o /usr/bin/mender-artifact && \
  curl -SL --fail "https://stress-client.s3-accelerate.amazonaws.com/release/mender-stress-test-client" \
  -o /usr/bin/mender-stress-test-client && \
  chmod +x /usr/bin/mender-artifact && \
  chmod +x /usr/bin/mender-stress-test-client

WORKDIR /e2e

COPY package-lock.json package.json ./
RUN npm ci
CMD npm run test