services:
    minio:
      image: alpine
      command: "true"
    mender-deployments:
        # HACK: Changing minio dependency condiditon to service_started allows
        #       us to scale the service to 0.
        depends_on:
          minio:
            condition: service_started
        environment:
            DEPLOYMENTS_STORAGE_DEFAULT: "azure"
            DEPLOYMENTS_STORAGE_BUCKET: ${AZURE_STORAGE_CONTAINER_NAME}
            DEPLOYMENTS_AZURE_AUTH_SHARED_KEY_ACCOUNT_NAME: ${AZURE_STORAGE_ACCOUNT_NAME}
            DEPLOYMENTS_AZURE_AUTH_SHARED_KEY_ACCOUNT_KEY: ${AZURE_STORAGE_ACCOUNT_KEY}
