services:
  mtls-gateway:
    image: registry.mender.io/mendersoftware/mender-gateway:master
    networks:
      - mender
    volumes:
      - ${MTLS_CERT:-./extra/mtls/certs/server/server.crt}:/etc/mtls/certs/server/server.crt:ro
      - ${MTLS_KEY:-./extra/mtls/certs/server/server.key}:/etc/mtls/certs/server/server.key:ro
      - ${MTLS_TENANT_CA:-./extra/mtls/certs/tenant-ca/tenant.ca.crt}:/etc/mtls/certs/tenant-ca/tenant.ca.crt:ro
    environment:
      UPSTREAM_SERVER_URL: "https://mender-api-gateway"
      MTLS_ENABLED: "true"
      HTTPS_ENABLED: "true"
      HTTPS_LISTEN: ":8080"
      MTLS_MENDER_USERNAME: "mtls@mender.io"
      MTLS_MENDER_PASSWORD: "correcthorsebatterystaple"
      MTLS_CA_CERTIFICATE: "/etc/mtls/certs/tenant-ca/tenant.ca.crt"
      HTTPS_SERVER_CERTIFICATE: "/etc/mtls/certs/server/server.crt"
      HTTPS_SERVER_KEY: "/etc/mtls/certs/server/server.key"
      UPSTREAM_SERVER_INSECURE_SKIP_VERIFY: "true"
    labels:
        - mender.testprefix=${MENDER_TESTPREFIX:-""}
