#
# Traefik static file configuration
#
providers:
  file:
    directory: '/etc/traefik/config'
    watch: true

experimental:
  http3: true

entryPoints:
  https:
    address: :443
    http3:
      advertisedPort: 443
    transport:
      respondingTimeouts:
        idleTimeout: 7200
        readTimeout: 7200
        writeTimeout: 7200

  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
          permanent: true

accessLog:
  format: json

api:
  dashboard: true
  insecure: true

log:
  level: DEBUG

ping: {}
