#!/bin/sh
#pulls a given file from the mender-buildsystem S3 bucket

if [ $# -ne 2 ];then
    echo "Usage: s3-get file output"
    exit -1
fi

if [ -z "$S3_KEY" -o -z "$S3_SECRET" ];then
    echo "Need S3_KEY and S3_SECRET environment variables"
    exit -1
fi

file=$1
bucket=mender-buildsystem
resource="/${bucket}/${file}"
contentType=application/x-compressed-tar
dateValue="`date -u +'%Y%m%dT%H%M%SZ'`"
stringToSign="GET

${contentType}
${dateValue}
${resource}"

signature=`/bin/echo -n "$stringToSign" | openssl sha1 -hmac ${S3_SECRET} -binary | base64`

curl -o "$2" \
     -f \
     -H "Host: ${bucket}.s3.amazonaws.com" \
     -H "Date: ${dateValue}" \
     -H "Content-Type: ${contentType}" \
     -H "Authorization: AWS ${S3_KEY}:${signature}" \
        https://${bucket}.s3.amazonaws.com/${file}
